
insert into employee values(1,'android','Alexei','Moiseenkov','senior java developer');
insert into employee values(2,'android','Alexandr','Velitchenko','junior java developer');
insert into employee values(3,'android','Michael','Shumachel','Ruby developer');
insert into employee values(4,'android','Richard','AnyLastName','junior Ruby developer');
insert into employee values(5,'android','Alexei','Maslykov','java developer');
insert into employee values(6,'android','Pasha','Meerovich','junior java developer');
insert into employee values(7,'android','Valera','Civinski','Ruby developer');
insert into employee values(8,'IOS','Denis','Syboch','senior Ruby developer');
insert into employee values(9,'IOS','Vlad','Krasov','junior Ruby developer');
insert into employee values(10,'IOS','Niko','Rosberg','senior Ruby developer');
insert into employee values(11,'IOS','Liuis','Hemilton','java developer');
insert into employee values(12,'IOS','Daniil','Kvyat','senior java developer');
insert into employee values(13,'IOS','Felippe','Massa','Ruby developer');
insert into employee values(14,'web','Maks','Ferstappen','junior C++ developer');
insert into employee values(15,'web','Valeri','Bottas','java developer');
insert into employee values(16,'web','Sahio','Peres','junior C++ developer');
insert into employee values(17,'web','Toto','Volf','senior java developer');
insert into employee values(18,'web','Artem','Matskel','junior java developer');
insert into employee values(19,'web','Artem','Kozlov','C++ developer');
insert into employee values(20,'web','Viktoria','Sevruk','C++ developer');
insert into employee values(21,'IOS','Katya','Kirilova','junior C++ developer');
insert into employee values(22,'IOS','Masha','NLO','Oracle db developer');
insert into employee values(23,'IOS','Ylia','Vashko','junior java developer');
insert into employee values(24,'web','Lilia','Manko','Piton developer');
insert into employee values(25,'web','Valera','Puhalski','java developer');
insert into employee values(26,'web','Evgeni','Denisov','java developer');
insert into employee values(27,'web','Maks','Petrochenko','senior Piton developer');
insert into employee values(28,'sience','Andrei','Orlov','junior Piton developer');
insert into employee values(29,'sience','Andrei','Popov','junior Piton developer');
insert into employee values(30,'sience','Veronika','Poplavskai','Piton developer');
insert into employee values(31,'sience','Vlad','Savostin','senior Piton developer');
insert into employee values(32,'sience','Masha','Plushenua','junior Piton developer');
insert into employee values(33,'sience','Bony','Stepanov','junior Oracle db developer');
insert into employee values(34,'android','Sergei','Moiseenkov','Oracle db developer');
insert into employee values(35,'android','Klavdia','Moiseenkova','Oracle db developer');
insert into employee values(36,'android','Ivan','Brundin','senior Ruby developer');
insert into employee values(37,'android','HZ','Zaicev','junior C++ developer');
insert into employee values(38,'android','Ekaterina','Kirilova','junior C++ developer');
insert into employee values(39,'web','Daniil','Kirilov','senior java developer');
insert into employee values(40,'web','Sergei','Kirilov','java developer');
insert into employee values(41,'web','Anatoli','Moiseenkov','java developer');
insert into employee values(42,'sience','Zinaida','Moiseenkova','senior java developer');
insert into employee values(43,'sience','Pavel','Sarviro','junior java developer');
insert into employee values(44,'android','Yaroslav','Sarviro','junior java developer');
insert into employee values(45,'android','Vova','Ivanov','senior C++ developer');
insert into employee values(46,'android','Marina','Rudenia','senior C++ developer');
insert into employee values(47,'android','Anastasia','Pruchkovaskay','junior C++ developer');


